---
# tasks file for test1

# set default vars. override in calling playbook
- set_fact:
    trigger_by_name: false
    trigger_as_listener: false

- name: trigger handler by name
  debug:
    msg: "triggering handle by name from role test1"
  changed_when: true
  notify: handle by name
  when: trigger_by_name

- name: trigger handler as listener
  debug:
    msg: "triggering handle as listener from role test1"
  changed_when: true
  notify: handle as listener
  when: trigger_as_listener
